# Generated by Django 5.2.15 on 2026-07-04 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('employee', 'Сотрудник')], default='employee', max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_memberships', to='branches.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='companies.company', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ пользователя',
                'verbose_name_plural': 'Доступы пользователей',
                'ordering': ['company', 'user'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='uniq_user_company_membership')],
            },
        ),
    ]
