# Generated by Django 5.2.15 on 2026-07-06 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('branches', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Имя сотрудника')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('employee', 'Сотрудник')], default='employee', max_length=20, verbose_name='Роль')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('cancelled', 'Отменено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='Статус')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен приглашения')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принято')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_invitations', to='branches.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_invitations', to='companies.company', verbose_name='Компания')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='Кто пригласил')),
            ],
            options={
                'verbose_name': 'Приглашение сотрудника',
                'verbose_name_plural': 'Приглашения сотрудников',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'email', 'status'), name='uniq_employee_invitation_state_per_company_email')],
            },
        ),
    ]
