# Generated by Django 5.2.15 on 2026-07-06 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('messengers', 'Мессенджеры')], max_length=20, verbose_name='Канал')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Тема')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('sent', 'Отправлена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Получателей')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланирована на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлена')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to='companies.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Маркетинговая кампания',
                'verbose_name_plural': 'Маркетинговые кампании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('email', 'Email рассылка'), ('sms', 'SMS рассылка'), ('messengers', 'Мессенджеры'), ('lookalike', 'Look-alike аудитория'), ('google_ads', 'Google Ads'), ('vk_ads', 'VK Реклама'), ('yandex_direct', 'Яндекс.Директ'), ('yandex_toloka', 'Яндекс.Толока'), ('repeat_deals', 'Повторные сделки')], max_length=30, verbose_name='Сервис')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Название')),
                ('status', models.CharField(choices=[('disconnected', 'Не подключено'), ('connected', 'Подключено'), ('pending', 'Ожидает проверки'), ('error', 'Ошибка')], default='disconnected', max_length=20, verbose_name='Статус')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_integrations', to='companies.company', verbose_name='Компания')),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_integrations', to=settings.AUTH_USER_MODEL, verbose_name='Подключил')),
            ],
            options={
                'verbose_name': 'Маркетинговая интеграция',
                'verbose_name_plural': 'Маркетинговые интеграции',
                'constraints': [models.UniqueConstraint(fields=('company', 'provider'), name='uniq_marketing_integration_per_company')],
            },
        ),
    ]
