# Generated by Django 5.2.15 on 2026-07-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('trainer_name', models.CharField(blank=True, max_length=120, verbose_name='Тренер')),
                ('room', models.CharField(blank=True, max_length=120, verbose_name='Зал')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(verbose_name='Окончание')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_events', to='branches.branch', verbose_name='Филиал')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_events', to='clients.client', verbose_name='Клиент')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Событие расписания',
                'verbose_name_plural': 'События расписания',
                'ordering': ['starts_at'],
            },
        ),
    ]
