# Generated by Django 5.2.15 on 2026-07-06 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_1c_import_fields'),
        ('companies', '0001_initial'),
        ('schedule', '0003_groupprogram_groupscheduleslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupscheduleslot',
            name='custom_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Своё название'),
        ),
        migrations.AddField(
            model_name='groupscheduleslot',
            name='max_participants',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Пусто — использовать значение из настроек компании.', null=True, verbose_name='Макс. участников'),
        ),
        migrations.CreateModel(
            name='ScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_max_participants', models.PositiveSmallIntegerField(default=20, verbose_name='Макс. участников по умолчанию')),
                ('sms_reminder_hours', models.JSONField(blank=True, default=list, help_text='Например: [24, 2] — за сутки и за 2 часа.', verbose_name='Напоминания SMS (часы до занятия)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_settings', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Настройки расписания',
                'verbose_name_plural': 'Настройки расписания',
            },
        ),
        migrations.CreateModel(
            name='ScheduleSmsIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('none', 'Не подключено'), ('sms_ru', 'SMS.ru'), ('smsc', 'SMSC.ru'), ('sms_aero', 'SMS Aero'), ('twilio', 'Twilio'), ('webhook', 'Webhook')], default='none', max_length=20, verbose_name='Провайдер')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Название')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='API Secret')),
                ('sender_name', models.CharField(blank=True, max_length=32, verbose_name='Имя отправителя')),
                ('webhook_url', models.URLField(blank=True, verbose_name='Webhook URL')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Доп. настройки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_sms_integrations', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'SMS-интеграция расписания',
                'verbose_name_plural': 'SMS-интеграции расписания',
                'ordering': ['-is_primary', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupSlotEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('waitlist', 'Лист ожидания')], default='confirmed', max_length=20, verbose_name='Статус')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_slot_enrollments', to='clients.client', verbose_name='Клиент')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_slot_enrollments', to='companies.company', verbose_name='Компания')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schedule.groupscheduleslot', verbose_name='Слот')),
            ],
            options={
                'verbose_name': 'Запись на групповое занятие',
                'verbose_name_plural': 'Записи на групповые занятия',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('slot', 'client'), name='uniq_group_slot_client')],
            },
        ),
    ]
