# Generated by Django 5.2.15 on 2026-07-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_groupscheduleslot_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupscheduleslot',
            name='color',
            field=models.CharField(blank=True, max_length=16, verbose_name='Цвет'),
        ),
    ]
