# Generated by Django 5.2.15 on 2026-07-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_groupscheduleslot_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesettings',
            name='embed_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Токен встраивания'),
        ),
        migrations.AddField(
            model_name='schedulesettings',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано на сайте'),
        ),
        migrations.AddField(
            model_name='schedulesettings',
            name='publish_weeks_ahead',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Недель в публичном виджете'),
        ),
    ]
