# Generated by Django 5.2.15 on 2026-07-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_schedule_publish_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupslotenrollment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтверждена'), ('completed', 'Проведена'), ('cancelled', 'Отменена'), ('waitlist', 'Лист ожидания')], default='confirmed', max_length=20, verbose_name='Статус'),
        ),
    ]
