# Generated by Django 5.2.15 on 2026-07-09 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_trainer_phone_optional'),
        ('schedule', '0008_alter_groupslotenrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprogram',
            name='room',
            field=models.CharField(blank=True, max_length=120, verbose_name='Зал'),
        ),
        migrations.AddField(
            model_name='groupprogram',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_programs', to='employees.trainer', verbose_name='Тренер'),
        ),
    ]
