# Generated by Django 5.2.15 on 2026-07-06 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, verbose_name='Номер')),
                ('prefix', models.CharField(blank=True, max_length=20, verbose_name='Префикс')),
                ('contract_date', models.DateField(verbose_name='Дата')),
                ('template_name', models.CharField(max_length=255, verbose_name='Бланк договора')),
                ('membership_label', models.CharField(blank=True, max_length=255, verbose_name='Членство, пакет услуг')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Подписан')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='branches.branch', verbose_name='Структурная единица')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client', verbose_name='Клиент')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='companies.company', verbose_name='Компания')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='memberships.membership', verbose_name='Абонемент')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-contract_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'number'), name='uniq_contract_number_per_company')],
            },
        ),
    ]
