# Generated by Django 5.2.15 on 2026-07-06 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('icloud', 'iCloud'), ('office365', 'Office365'), ('exchange', 'Exchange'), ('yahoo', 'Yahoo!'), ('aol', 'Aol'), ('yandex', 'Яндекс'), ('mailru', 'Mail.ru'), ('imap', 'Корпоративная почта')], max_length=20, verbose_name='Провайдер')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name='Отображаемое имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_accounts', to='companies.company', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Почтовый ящик',
                'verbose_name_plural': 'Почтовые ящики',
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.CharField(choices=[('inbox', 'Входящие'), ('sent', 'Отправленные'), ('drafts', 'Черновики'), ('trash', 'Корзина')], default='inbox', max_length=20, verbose_name='Папка')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст')),
                ('from_name', models.CharField(blank=True, max_length=120, verbose_name='От кого (имя)')),
                ('from_email', models.EmailField(max_length=254, verbose_name='От кого')),
                ('to_emails', models.TextField(help_text='Список email через запятую', verbose_name='Кому')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('sent_at', models.DateTimeField(verbose_name='Дата')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailbox.mailaccount', verbose_name='Ящик')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mailaccount',
            constraint=models.UniqueConstraint(fields=('company', 'user', 'email'), name='uniq_mail_account_per_user'),
        ),
    ]
