# Generated by Django 5.2.15 on 2026-07-06 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('item_type', models.CharField(choices=[('folder', 'Папка'), ('file', 'Файл')], max_length=10, verbose_name='Тип')),
                ('file', models.FileField(blank=True, null=True, upload_to='drive/%Y/%m/', verbose_name='Файл')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='MIME')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Размер')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='В корзине')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_items', to='companies.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_items', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drive.driveitem', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Элемент диска',
                'verbose_name_plural': 'Элементы диска',
                'ordering': ['item_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'parent', 'name', 'is_trashed'), name='uniq_drive_item_name_per_folder')],
            },
        ),
    ]
