resolver 127.0.0.11 valid=10s ipv6=off;
resolver_timeout 5s;

upstream crm_frontend {
    zone crm_frontend 64k;
    server frontend:3000 resolve;
}

upstream crm_backend {
    zone crm_backend 64k;
    server backend:8000 resolve;
}

server {
    listen 80;
    server_name crm.sportmax.fit schedule.sportmax.fit lk.sportmax.fit sport-max.com.ru www.sport-max.com.ru;

    if ($scanner_ip_blocked) { return 444; }
    if ($scanner_uri_blocked) { return 444; }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 80 default_server;
    server_name _;

    if ($scanner_ip_blocked) { return 444; }
    return 444;
}
