# Generated by Django 5.2.15 on 2026-07-07 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mango', 'Mango Office'), ('sigur', 'Sigur'), ('rfid', 'RFID'), ('turnstile', 'Турникеты'), ('payment', 'Платёжный сервис'), ('sms', 'SMS'), ('partner', 'Партнёрский адаптер')], max_length=40, verbose_name='Провайдер')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('error', 'Ошибка'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('external_id', models.CharField(blank=True, max_length=120, verbose_name='Внешний ID')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Интеграция',
                'verbose_name_plural': 'Интеграции',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mango', 'Mango Office'), ('sigur', 'Sigur'), ('rfid', 'RFID'), ('turnstile', 'Турникеты'), ('payment', 'Платёжный сервис'), ('sms', 'SMS'), ('partner', 'Партнёрский адаптер')], max_length=40, verbose_name='Провайдер')),
                ('direction', models.CharField(choices=[('inbound', 'Входящее'), ('outbound', 'Исходящее')], default='inbound', max_length=20, verbose_name='Направление')),
                ('event_type', models.CharField(max_length=120, verbose_name='Тип события')),
                ('status', models.CharField(choices=[('received', 'Получено'), ('processed', 'Обработано'), ('failed', 'Ошибка')], default='received', max_length=20, verbose_name='Статус')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('external_key', models.CharField(blank=True, max_length=128, verbose_name='Внешний ключ')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Получено в')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано в')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_events', to='companies.company', verbose_name='Компания')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='integrations.integrationconnection', verbose_name='Интеграция')),
            ],
            options={
                'verbose_name': 'Событие интеграции',
                'verbose_name_plural': 'События интеграций',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('company', 'provider', 'external_id'), name='uniq_integration_external_id_per_company'),
        ),
    ]
