# Generated by Django 5.2.15 on 2026-07-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название абонемента')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('frozen', 'Заморожен'), ('expired', 'Истёк'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('starts_at', models.DateField(verbose_name='Дата начала')),
                ('ends_at', models.DateField(verbose_name='Дата окончания')),
                ('visit_limit', models.PositiveIntegerField(blank=True, help_text='Пустое значение означает безлимитный абонемент.', null=True, verbose_name='Лимит посещений')),
                ('visits_used', models.PositiveIntegerField(default=0, verbose_name='Использовано посещений')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_records', to='branches.branch', verbose_name='Филиал')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clients.client', verbose_name='Клиент')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['-starts_at', 'client'],
            },
        ),
    ]
