# Generated by Django 5.2.15 on 2026-07-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_1c_import_fields'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephonyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('none', 'Не подключено'), ('mango', 'Mango Office'), ('binotel', 'Binotel'), ('zadarma', 'Zadarma'), ('webhook', 'Webhook')], default='none', max_length=20, verbose_name='Провайдер')),
                ('api_url', models.URLField(blank=True, default='https://app.mango-office.ru/vpbx', verbose_name='API URL')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='API Salt')),
                ('webhook_secret', models.CharField(blank=True, max_length=64, verbose_name='Webhook secret')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Доп. настройки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telephony_integration', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Интеграция телефонии',
                'verbose_name_plural': 'Интеграции телефонии',
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Внешний ID')),
                ('direction', models.CharField(choices=[('incoming', 'Входящий'), ('outgoing', 'Исходящий')], default='incoming', max_length=20, verbose_name='Направление')),
                ('status', models.CharField(choices=[('answered', 'Отвечен'), ('missed', 'Пропущен'), ('busy', 'Занято'), ('voicemail', 'Голосовая почта')], default='answered', max_length=20, verbose_name='Статус')),
                ('caller_phone', models.CharField(blank=True, max_length=32, verbose_name='Номер звонящего')),
                ('target_phone', models.CharField(blank=True, max_length=32, verbose_name='Номер назначения')),
                ('from_number', models.CharField(blank=True, max_length=64, verbose_name='From (сырой)')),
                ('to_number', models.CharField(blank=True, max_length=64, verbose_name='To (сырой)')),
                ('line_number', models.CharField(blank=True, max_length=64, verbose_name='Линия (номер)')),
                ('line_name', models.CharField(blank=True, max_length=120, verbose_name='Линия')),
                ('recording_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='ID записи')),
                ('recording_url', models.URLField(blank=True, verbose_name='Ссылка на запись')),
                ('started_at', models.DateTimeField(verbose_name='Начало')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='Источник')),
                ('transcription_text', models.TextField(blank=True, verbose_name='Транскрипция')),
                ('call_summary', models.CharField(blank=True, max_length=500, verbose_name='Краткое резюме')),
                ('call_report', models.TextField(blank=True, verbose_name='AI-отчёт')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='clients.client', verbose_name='Клиент')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'ordering': ['-started_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('company', 'external_id'), name='uniq_call_external_id_per_company')],
            },
        ),
    ]
