# Generated by Django 5.2.15 on 2026-07-07 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_club_access_blocked_and_more'),
        ('companies', '0003_company_role_disabled_modules_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('max', 'МАКС'), ('telegram', 'Телеграм'), ('whatsapp', 'Вотсапп')], max_length=32, verbose_name='Провайдер')),
                ('external_chat_id', models.CharField(db_index=True, max_length=128, verbose_name='ID чата')),
                ('external_user_id', models.CharField(blank=True, max_length=128, verbose_name='ID пользователя')),
                ('chat_type', models.CharField(blank=True, max_length=32, verbose_name='Тип чата')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Имя контакта')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон контакта')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение')),
                ('last_message_preview', models.CharField(blank=True, max_length=255, verbose_name='Превью')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='Непрочитанные')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_threads', to='clients.client', verbose_name='Клиент')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_threads', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Диалог мессенджера',
                'verbose_name_plural': 'Диалоги мессенджеров',
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MessengerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('inbound', 'Входящее'), ('outbound', 'Исходящее')], max_length=16, verbose_name='Направление')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Внешний ID')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырой payload')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels.messengerthread', verbose_name='Диалог')),
            ],
            options={
                'verbose_name': 'Сообщение мессенджера',
                'verbose_name_plural': 'Сообщения мессенджеров',
                'ordering': ['sent_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessengerIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('max', 'МАКС'), ('telegram', 'Телеграм'), ('whatsapp', 'Вотсапп')], max_length=32, verbose_name='Провайдер')),
                ('bot_token', models.CharField(blank=True, max_length=512, verbose_name='Токен бота')),
                ('webhook_secret', models.CharField(blank=True, max_length=256, verbose_name='Секрет webhook')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_integrations', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Интеграция мессенджера',
                'verbose_name_plural': 'Интеграции мессенджеров',
                'constraints': [models.UniqueConstraint(fields=('company', 'provider'), name='uniq_messenger_integration_company_provider')],
            },
        ),
        migrations.AddConstraint(
            model_name='messengerthread',
            constraint=models.UniqueConstraint(fields=('company', 'provider', 'external_chat_id'), name='uniq_messenger_thread_external_chat'),
        ),
        migrations.AddConstraint(
            model_name='messengermessage',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('thread', 'external_id'), name='uniq_messenger_message_external_id'),
        ),
    ]
