# Generated by Django 5.2.16 on 2026-07-07 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('companies', '0003_company_role_disabled_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerintegration',
            name='connection_mode',
            field=models.CharField(choices=[('bot', 'Бот'), ('gateway', 'Личный аккаунт')], default='gateway', max_length=16, verbose_name='Режим подключения'),
        ),
        migrations.CreateModel(
            name='MessengerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('max', 'МАКС'), ('telegram', 'Телеграм'), ('whatsapp', 'Вотсапп')], max_length=32, verbose_name='Провайдер')),
                ('gateway_session_id', models.CharField(max_length=128, unique=True, verbose_name='ID сессии шлюза')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Название')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон аккаунта')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('qr', 'Сканируйте QR'), ('code_required', 'Нужен код'), ('password_required', 'Нужен пароль 2FA'), ('ready', 'Подключён'), ('error', 'Ошибка'), ('disconnected', 'Отключён')], default='pending', max_length=32, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='Подключён')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_accounts', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Аккаунт мессенджера',
                'verbose_name_plural': 'Аккаунты мессенджеров',
                'ordering': ['-connected_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='messengerthread',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='channels.messengeraccount', verbose_name='Аккаунт'),
        ),
    ]
