# Generated by Django 5.2.15 on 2026-07-07 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=120, verbose_name='Тип события')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'В обработке'), ('done', 'Выполнено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('source_app', models.CharField(blank=True, max_length=120, verbose_name='Источник')),
                ('source_model', models.CharField(blank=True, max_length=120, verbose_name='Модель источника')),
                ('source_object_id', models.CharField(blank=True, max_length=64, verbose_name='ID источника')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано в')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_events', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_events', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Событие автоматизации',
                'verbose_name_plural': 'События автоматизации',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('event_type', models.CharField(db_index=True, max_length=120, verbose_name='Тип события')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='Условия')),
                ('actions', models.JSONField(blank=True, default=list, verbose_name='Действия')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Правило автоматизации',
                'verbose_name_plural': 'Правила автоматизации',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
