# Generated by Django 5.2.15 on 2026-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('checked_in', 'Пришёл'), ('late', 'Опоздал'), ('no_show', 'Не пришёл'), ('cancelled', 'Отменено')], default='checked_in', max_length=20, verbose_name='Статус')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Время входа')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Время выхода')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-checked_in_at', '-created_at'],
            },
        ),
    ]
