# Generated by Django 5.2.15 on 2026-07-06 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('bookings', '0001_initial'),
        ('branches', '0001_initial'),
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_record', to='bookings.booking', verbose_name='Бронирование'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='branches.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='memberships.membership', verbose_name='Абонемент'),
        ),
    ]
