# Generated by Django 5.2.15 on 2026-07-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='locker_key',
            field=models.CharField(blank=True, max_length=32, verbose_name='Ключ/шкафчик'),
        ),
    ]
