# Generated by Django 5.2.15 on 2026-07-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL-идентификатор')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной филиал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['company', 'name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'slug'), name='uniq_branch_slug_per_company')],
            },
        ),
    ]
