# Generated by Django 5.2.15 on 2026-07-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_1c_import_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='club_access_blocked',
            field=models.BooleanField(default=False, verbose_name='Блок доступа в клуб'),
        ),
        migrations.AddField(
            model_name='client',
            name='group_programs_blocked',
            field=models.BooleanField(default=False, verbose_name='Блок групповых программ'),
        ),
    ]
