# Generated by Django 5.2.15 on 2026-07-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='disabled_modules',
            field=models.JSONField(blank=True, default=list, help_text='Идентификаторы пунктов бокового меню, скрытых для сотрудников компании.', verbose_name='Скрытые модули меню'),
        ),
    ]
