# Generated by Django 5.2.15 on 2026-07-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_disabled_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='role_disabled_modules',
            field=models.JSONField(blank=True, default=dict, help_text='Словарь {роль: [id пунктов меню]} — что дополнительно скрыто для конкретной роли.', verbose_name='Скрытые модули меню по ролям'),
        ),
        migrations.AlterField(
            model_name='company',
            name='disabled_modules',
            field=models.JSONField(blank=True, default=list, help_text='Идентификаторы пунктов бокового меню, скрытых для всех сотрудников компании.', verbose_name='Скрытые модули меню'),
        ),
    ]
