# Generated by Django 5.2.15 on 2026-07-06 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('specialization', models.CharField(blank=True, max_length=255, verbose_name='Специализация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='branches.branch', verbose_name='Филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'phone'), name='uniq_trainer_phone_per_company')],
            },
        ),
    ]
