# Generated by Django 5.2.15 on 2026-07-07 06:38

import django.db.models.deletion
from django.db import migrations, models


def backfill_trainer_types(apps, schema_editor):
    Trainer = apps.get_model("employees", "Trainer")
    Trainer.objects.filter(trains_gym_floor=False, trains_group_programs=False).update(
        trains_gym_floor=True,
        trains_group_programs=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trains_group_programs',
            field=models.BooleanField(default=False, verbose_name='Групповые программы'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trains_gym_floor',
            field=models.BooleanField(default=False, verbose_name='Тренажёрный зал'),
        ),
        migrations.CreateModel(
            name='TrainerRentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(help_text='Хранится как первое число месяца', verbose_name='Месяц аренды')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('paid_at', models.DateTimeField(verbose_name='Дата оплаты')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_rent_payments', to='companies.company', verbose_name='Компания')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='employees.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Оплата аренды тренера',
                'verbose_name_plural': 'Оплаты аренды тренеров',
                'ordering': ['-period', '-paid_at'],
                'constraints': [models.UniqueConstraint(fields=('trainer', 'period'), name='uniq_trainer_rent_period')],
            },
        ),
        migrations.RunPython(backfill_trainer_types, migrations.RunPython.noop),
    ]
