# Generated by Django 5.2.15 on 2026-07-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_trainer_trains_group_programs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='achievements',
            field=models.TextField(blank=True, verbose_name='Заслуги и регалии'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='bio',
            field=models.TextField(blank=True, help_text='Публичное описание тренера — выгружается на сайт и в приложение.', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/%Y/%m/', verbose_name='Фото'),
        ),
    ]
