# Generated by Django 5.2.15 on 2026-07-07 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_disabled_modules'),
        ('employees', '0003_trainer_achievements_trainer_bio_trainer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAccessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(max_length=64, verbose_name='Номер карты')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('blocked', 'Заблокирована'), ('lost', 'Утеряна')], default='active', max_length=20, verbose_name='Статус')),
                ('issued_at', models.DateTimeField(verbose_name='Дата выдачи')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_access_cards', to='companies.company', verbose_name='Компания')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_cards', to='employees.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Карта доступа тренера',
                'verbose_name_plural': 'Карты доступа тренеров',
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'card_number'), name='uniq_trainer_card_number_per_company')],
            },
        ),
    ]
